넘파이 라이브러리 호출

In [3]:
import numpy as np

In [10]:
weight_vector = np.array([[1], [1], [1]]) # Weight Vector 
x_vector = np.array([[3], [4], [5]])

weight_vector

array([[1],
       [1],
       [1]])

In [11]:
x_vector

array([[3],
       [4],
       [5]])

Weight Vector는 원래 학습을 통해 얻어져야 하지만 모델 표현을 위해 그냥 넣었다.

곱하기 위해 Weight Vector를 트랜스포즈 시킴

In [12]:
weight_vector.T

array([[1, 1, 1]])

In [13]:
weight_vector.T.dot(x_vector)

array([[12]])

weight_vector를 트랜스포즈 시킨후 x_vector와 dot product함 

1X 3 + 1 X 4 + 1 X 5 = 12

### Pandas로 데이터 불러와서 numpy로 모델 만들기

y= W * X + b 로 나타낼 것이다.

pandas 호출

In [14]:
import pandas as pd

데이터 불러오기

csv 타입 데이터 로드, separate는 빈공간으로 지정하고, Column은 없음

ML_1.Pandas 참고

In [15]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data' #Data URL
df_data = pd.read_csv(data_url, sep='\s+', header = None) 
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV'] 
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

상수항(W=y= W * X + b에서 b)은 weight가 1이다.  

weight 0의 값 추가해야 한다.

In [16]:
df_data['weight_0'] = 1

MEDV는 y값이므로 모델을 표현할때 없어도된다.

In [17]:
df_data= df_data.drop("MEDV", axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

이제 위 표를 matrix로 변환한다.

아직 weight는 학습시키지 않았으므로 랜덤값을 사용한다.

In [21]:
df_matrix = df_data.as_matrix() 
weight_vector =  np.random.random_sample((14, 1)

df_matrix가 X이며 weight_vector가 W이다.

이제 곱하면 모델이 완성된다.

In [22]:
df_matrix.dot(weight_vector)

array([[ 105.74164674],
       [  94.85795045],
       [  92.48629915],
       [  84.60010108],
       [  85.95436453],
       [  86.05641336],
       [ 116.76396485],
       [ 121.13746406],
       [ 123.02883983],
       [ 119.88318017],
       [ 121.42850162],
       [ 118.87791388],
       [ 114.2917422 ],
       [ 113.79085048],
       [ 116.26112465],
       [ 113.13565036],
       [ 110.41762019],
       [ 116.74358172],
       [ 110.36029803],
       [ 114.65414494],
       [ 119.45369189],
       [ 117.4021939 ],
       [ 118.89470015],
       [ 119.58521573],
       [ 118.34244324],
       [ 116.66218959],
       [ 117.54808816],
       [ 117.41807743],
       [ 118.03789579],
       [ 117.3210905 ],
       [ 119.24161823],
       [ 118.85681794],
       [ 117.87504101],
       [ 118.50316082],
       [ 118.60280291],
       [ 105.23132992],
       [ 104.62555768],
       [ 102.5406063 ],
       [ 101.65927153],
       [ 109.42639402],
       [ 108.61621993],
       [  85.390

In [23]:
df_matrix.dot(weight_vector).shape

(506, 1)