In [2]:
import tensorflow as tf
import numpy as np

# Softmax Regression - Multinomial classification

## 예제

### data

In [15]:
Learning_rate = 0.01
nb_classes = 3


x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data =[[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

### placeholder

In [7]:
X=tf.placeholder(tf.float32,shape=[None,4])
Y=tf.placeholder(tf.float32,shape=[None,3])

W= tf.Variable(tf.random_normal([4,nb_classes],name='weight'))
b=tf.Variable(tf.random_normal([nb_classes],name='bias'))

### Hypothesis
tf.nn.softmax compputes softmax activation

softmax=exp(Logit)/reduce_sum(exp(Logit),dim)

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

### Cost/Loss funcion
Cross entropy cost/loss

In [11]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate =Learning_rate).minimize(cost)

### Graph

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

### Training

In [17]:
feed_dict ={X: x_data, Y: y_data}

for i in range(2001):
    sess.run(optimizer,feed_dict=feed_dict)
    if i %200 ==0:
        print(i, sess.run(cost, feed_dict=feed_dict))

0 0.458581
200 0.44627
400 0.43519
600 0.425105
800 0.415837
1000 0.407248
1200 0.39923
1400 0.391702
1600 0.384593
1800 0.377853
2000 0.371435


### Testting 

In [19]:
a = sess.run(hypothesis, feed_dict={X: [[1,11,7,9],[1,3,4,3],[1,1,0,1]]} )
print(a, sess.run(tf.argmax(a,1)))

[[  3.97368640e-01   6.01973653e-01   6.57721655e-04]
 [  5.29837668e-01   3.87698114e-01   8.24641883e-02]
 [  8.06823256e-04   1.90920979e-02   9.80101109e-01]] [1 0 2]
