## indexing

넘파이는 list와 달리 [0,0]같은 표기법을 제공한다.

Matrix를 예로 들자면 앞은 row, 뒤는 column이다.

In [3]:
import numpy as np

2 * 3  Matrix로 예를 들어보자

In [2]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

List의 [0][0]과 numpy의 [0,0]은 같다

In [5]:
print(test_exmaple[0][0])
print(test_exmaple[0,0])

1
1


원하는 원소에 값을 할당시켜줄려면(넣어줄려면) 어떻게 해야 할까?

간단하다.

원하는배열.[row,column]= 원하는값 으로 해주면된다.

예시로 [0,0]에 12를 넣어주자

In [6]:
test_exmaple[0,0] = 12
test_exmaple

array([[12,  2,  3],
       [ 4,  5,  6]])

List의 [0][0]도 같은 효과를 볼 수 있다.

In [7]:
test_exmaple[0][0] = 5 
test_exmaple[0,0]

5

## slicing

이미 있는 배열에서 부분집합을 빼오는거라고 생각하면 된다.

임의의 배열을 아래와 같다고 해보자

In [11]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


첫번째로 row는 다 빼오고, column은 2번째부터 빼오자고 해보자.

단, 이때 python에서는 숫자를 0부터 카운트하는것을 꼭 주의하자. 첫번째 coulmn은 1번이 아니라 0이다.

In [13]:
a[:,2:] 

array([[ 3,  4,  5],
       [ 8,  9, 10]])

이번엔 1번 row의 1~2 column을 빼오자.

이때 column을 1:3으로 하면 1부터 3미만이라고 생각하면된다.(3은 포함되지 않는다)

In [17]:
a[1,1:3]

array([7, 8])

아래 같은 경우는 comlumn을 따로 지정안해서 전부 출렸됬다.

만약에 row가 1까지 있는데 그 이상 출력하라고 하면?

In [16]:
a[1:2]

array([[ 6,  7,  8,  9, 10]])

있는거 까지만 출력된다.

2칸씩 띄우기


In [15]:
a[1,::2]

array([ 6,  8, 10])