# 2.Numpy

파이썬버전: 3.6.0

### 넘파이는 행렬 계산에 유용한 라이브러리이다.

## 2.0.0 라이브러리 불러오기
파이썬의 장점은 수많은 라이브러리가 있다는 점이다.
라이브러리가 있어서 텍스트 여러줄을 써야할것을 간편하게 한두줄로 줄일 수 있다.

In [76]:
improt numpy as np

위 코드로 numpy 코드를 불러왔다.

numpy 라이브러리를 import하여 파이썬 코드를 작성할때 사용할 수 있게 한다.

그리고 사용할 numpu 함수 앞에 np. 을 붙이면 된다.

확인해 보기 위해 2x2 행렬을 넘파이로 만들어보자

In [14]:
M=np.array([[1,2],[3,4]])
print(M)

[[1 2]
 [3 4]]


만약 함수 앞에 np. 붙이는것이 귀찮다면 'from numpy import * ' 로 입력해주면 된다.

In [65]:
from numpy import *
M=np.array([[1,2],[3,4]])
print('M=',M)

M= [[1 2]
 [3 4]]


### 예제:  다음의 sin값들을 계산하라
pi/6, pi/5, pi/4, pi/3, pi/2



In [57]:
x= array([pi/6,pi/5,pi/5,pi/3,pi/2])       #pi는 numpy에서 자동으로 3.14로 불러와진다.
print(sin(x))

[ 0.5         0.58778525  0.58778525  0.8660254   1.        ]


## 2.1 행렬

행렬과 관련된 파이썬 코드를 알아보자

### 1.행렬의 정수배

In [24]:
print(M*3)

[[ 3  6]
 [ 9 12]]


행렬의 정수배는 원하는 행렬 앞에 숫자를 곱해주면 된다.

### 2.행렬의 덧셈

In [66]:
print(M+M)

[[2 4]
 [6 8]]


### 3.행렬의 곱셈

In [67]:
print(M*M)

[[ 1  4]
 [ 9 16]]


여기서 곱셈은 dot product나 cross product가 아니라 같은 위치의 원소끼리 곱하는 것이다.

### 4.cross product (벡터 곱)

In [32]:
print(cross(M,M))

[0 0]


### 5.dot product( 스칼라 곱)

In [38]:
print(dot(M,M))

[[ 7 10]
 [15 22]]


### 6.전치행렬(Transpose)

In [39]:
print(transpose(M))

[[1 3]
 [2 4]]


역행렬, 고유치, 고유벡터, 그리고 행렬을 이용해 연립방정식을 푸는 선형대수적 문제들은 추가적으로 numpy.linalg을 불러와야 한다. 

In [40]:
from numpy.linalg import*

### 7.역행렬

In [43]:
print(inv(M))

[[-2.   1. ]
 [ 1.5 -0.5]]


### 8.디터미넌트

In [45]:
print(det(M))

-2.0


### 9.고유값,고유벡터

In [50]:
print(eig(M))

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


array가 두개 출력 되는데 앞에 array 가 고유값, 뒤의 array가 고유값에 따른 고유벡터들이다.

### 10.연립방정식계산하기

아래와 같은 연립방정식이 있다.
![m1.PNG](./image/m1.png)

이것을 행렬로 나타내면 아래와 같다.
![m2.PNG](./image/m2.png)

왼쪽 계수행렬을 M, 미지수를 x, 결과를 b로 놓은다면 우리는 아래의 식을 푸는 것이다.
![m3.PNG](./image/m3.png)

이제 파이썬으로 풀어보자

In [74]:
M = array ( [ [ 1 , 3 , -5 , 2 ] , [ 0 , 4 , -2 , 1 ] , [2 , -1 ,3 , -1] , [ 1 , 1 , 1 , 1 ] ] )
b = array ( [ 0 , 6 , 5 , 10 ] )
x = linalg.solve(M, b)
print(x)

[ 1.  2.  3.  4.]


우리는 이제 연립방정식을 해로 나타내서 간단하게 풀 수 있다.

### 예제: 키르히 호프 법칙

In [77]:
A= np.array([[-13,2,4],[2,-11,6],[4,6,-15]])
B=np.array([5,-10,5])
print('X=',np.linalg.solve(A,B)) 

X= [-0.28624535  0.81040892 -0.08550186]


## 2.2 그외 함수
넘파이에서 행렬의 성질 이외에 함수를 알아보자

### 1.arange(a,b,c)

a부터 b미만의 숫자를 c간격으로 생성한다

간단하게 '0부터 1까지 0.25 간격으로 생성해보자

In [70]:
print (arange ( 0 , 1 , 0.25 ))

[ 0.    0.25  0.5   0.75]


1미만이기 때문에 1은 포함되지 않는다. 
1도 포함하고 싶다면 아래처럼 쓰면 된다.

In [71]:
print (arange ( 0 , 1.01 , 0.25 ))

[ 0.    0.25  0.5   0.75  1.  ]


### 2.logspace(a,b,c)

logspace는 상용로그를 나열한다고 생각하면된다.

간단한 예시로 알아보자


In [72]:
print (logspace( 0 , 3 , 4))

[    1.    10.   100.  1000.]


10의 0제곱부터 10의 3제곱까지 4개 나열했다.

### 3.zeros

영행렬을 생성한다. 이때 기본적으로는 int타입이지만 소수점을 원하면 type을 double로 해주면된다.

2X3의 영행렬을 생성해보자

In [75]:
print (zeros( [ 2 , 3 ],int ))

[[0 0 0]
 [0 0 0]]


### 그 외 함수들은 https://docs.scipy.org/doc/numpy-dev/user/quickstart.html 를 참고하면 된다.