In [14]:
import numpy as np

이번에는 배열을 만들때 사용하는 함수를 알아보자

## arange

List의 range와 같다.

아래는 0부터 30개의 배열을 만들어낸다.

In [2]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

범위도 지정해줄 수 있으며 간격도 지정해 줄 수 있다.
0부터 5까지 0.5간격으로 만들어보자

In [3]:
np.arange(0, 5, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

앞에서 배운것처럼 만든 배열을 reshape 할 수 있다.

단, 이때 배열의 원소 갯수랑 모양이랑 맞아야한다.

In [5]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## ones, zeros, empty
1또는 0으로 채움

0만 있는 배열을 만들어보자

In [6]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

1만 있는 배열을 만들어 보자

In [8]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [9]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

empty는 shape만 있고 비어있는 배열을 만든다.

단 이때 메모리를 초기화시키지 않는다.

In [10]:
np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [11]:
np.empty((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

## something_like

ones나 zeors또는 empty를 사용할때, 기존 ndarry와 shpae를 같게해준다.

In [12]:
test_matrix = np.arange(30).reshape(5,6)

위와 같은 matrix가 있다면, 같은 모양의 zeros를 출력해보자

In [13]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## identity

단위 행렬을 만들어준다.

n으로 배열의 크기를 정해줄 수 있다

In [15]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [17]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## eye 

대각선이 1인 행렬을 만든다.

N으로 row, M으로 column의 크기를 정할 수 있으며, k로 어디서 시작할지 정할 수 있다.

In [18]:
np.eye(N=3, M=5, dtype=np.int8)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [19]:
np.eye(3,5,k=2)


array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## dig

matrix의 대각선 원소만 출력한다. 

In [22]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
np.diag(matrix)

array([0, 4, 8])

k로 시작하는 index를 지정해 줄 수 있다.

In [24]:
np.diag(matrix, k=1)

array([1, 5])

## random sampling

데이터 분포에 다른 sampling으로 array를 생성한다.

uniform은 균등분포를 생성한다.

In [26]:
np.random.uniform(0,1,10).reshape(2,5)

array([[ 0.4262347 ,  0.35835456,  0.97028799,  0.23572467,  0.6420314 ],
       [ 0.04291056,  0.49156391,  0.70757383,  0.70558041,  0.77488269]])

normal은 정규분포로 생성한다.

In [27]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.43780529, -0.29696535,  1.55993646,  0.67060473, -0.59596593],
       [ 1.66815566,  1.29058271, -0.81238136, -1.48390723,  0.29004588]])