In [4]:
import numpy as np

# operation in array

## sum

In [2]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
test_array.sum(dtype=np.float)

55.0

## axis
: 모든 operation funcion을 실행할 때, 기준이 되는 dimenstion 축

In [5]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
test_array.shape

(3, 4)

3의 axis=0, 4의 axis=1

In [8]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

axis 0 축을 기준으로 숫자를 다합쳤을때는 [15, 18, 21, 24]

axis 1 축을 기준으로  숫자를 다합쳤을때는 [10, 26, 42]

당연히 텐서에서도 사용가능

In [9]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [10]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [12]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [13]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

## 통계


In [14]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

평균


In [15]:
test_array.mean()

6.5

마찬가지로 축의 평균을 계산할 수 있다.

In [16]:
test_array.mean(axis=0)

array([ 5.,  6.,  7.,  8.])

표준편차

In [17]:
test_array.std()

3.4520525295346629

In [18]:
test_array.std(axis=0)

array([ 3.26598632,  3.26598632,  3.26598632,  3.26598632])

그외 exp이나 sqrt 등등이 있음

In [20]:
np.exp(test_array), np.sqrt(test_array)

(array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
           5.45981500e+01],
        [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
           2.98095799e+03],
        [  8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
           1.62754791e+05]]),
 array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
        [ 2.23606798,  2.44948974,  2.64575131,  2.82842712],
        [ 3.        ,  3.16227766,  3.31662479,  3.46410162]]))

## Concatenate
넘파이를 합침

vstack : 수직적으로 합침


In [21]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

hstack: 수평으로 합침

In [23]:
a = np.array([ [1], [2], [3]])
print(a)
b = np.array([ [2], [3], [4]])
print(b)

[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


In [24]:
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [25]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [27]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [28]:
a.tolist()


[[1, 2], [3, 4]]