In [4]:
import numpy as np

test_a = np.array([[1,2,3],[4,5,6]], float)
print(test_a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


## Element-wise operation
array간 shape가 같을때 일어나는 연산을 Element-wise operation이라고 한다.

넘파이는 array간의 기본적인 사칙연산을 지원함

In [3]:
test_a + test_a

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [6]:
test_a - test_a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])


곱셈은 같은 위치에 있는 element끼리 애들끼리 곱함

이것을 Element-wise product라고 한다



In [7]:
test_a * test_a

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [11]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

## Dot product
matrix의 기본 연산으로 dot 함수를 사용한다.

In [15]:
test_a = np.arange(1,7).reshape(2,3)
print(test_a)
test_b = np.arange(7,13).reshape(3,2)
print(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [16]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [17]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

Transpose : transpose 함수를 씀 또는 .T

In [20]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

또는 .T를 붙여서 나타낼 수 도 있다.

In [19]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

같은 매트릭스끼리 dot을 할려면 하나를 트랜스포즈 시켜줘야한다.

In [22]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## bordcasting
shape가 다른애들끼리 연산을 자동으로 지월하는 기능

In [24]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
print(test_matrix)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


Matrix 와 Scalar 덧셈

In [25]:
test_matrix + scalar

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

뺄셈

In [27]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

곱셈

In [28]:
test_matrix * 5 

array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

나눗셈

In [29]:
test_matrix / 5

array([[ 0.2,  0.4,  0.6],
       [ 0.8,  1. ,  1.2]])

몫

In [30]:
test_matrix // 0.2

array([[  4.,   9.,  14.],
       [ 19.,  24.,  29.]])

제곱

In [31]:
test_matrix ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

스칼라와 벡터 이외에도 벡터와 매트릭스 간의 연산도 지원한다.

In [33]:
test_matrix = np.arange(1,13).reshape(4,3)
print(test_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
test_vector = np.arange(10,40,10)
print(test_vector)

[10 20 30]


In [35]:
test_matrix+ test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

## numpy performance
계산할때 넘파이를 이용할때와 안할때의 시간이 얼마나 걸리는지 체크해보자

%timeit을 이용하면됨

첫번째는 for loop를 이용해서 체크해보자

In [1]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result 

iternation_max = 100000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) 

10.9 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


list comprehension을 이용한 성능체크

In [2]:
%timeit [scalar * value for value in range(iternation_max)] 

7.48 ms ± 52.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


넘파이를 이용한 성능 체크

In [5]:
%timeit np.arange(iternation_max) * scalar 

125 µs ± 586 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
