# All & Any
Array의 전부(and)또는 일부(or)가 조건에 만족 여부 반환

In [1]:
import numpy as np

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a<0

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

any: 하나라도 조건에 만족한다면 true

or 조건임

In [3]:
np.any(a>5), np.any(a<0)

(True, False)

all: 모두가 조건에 만족한다면 true

In [4]:
np.all(a>5) , np.all(a < 10)

(False, True)

# comparision operation #1

넘파이는 배열의 크기가 동일할때 원소간 비교의 결과를 불리언타입으로 출력

In [5]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False], dtype=bool)

같은지도 확인 할 수 있음

In [6]:
test_a == test_b

array([False, False, False], dtype=bool)

위에서 썼던 any도 사용할 수 있다.

In [7]:
(test_a > test_b).any() # 하나라도 만족하면 true

True

# comparision operation #2

logical_and: 괄호 안에 있는 두조건을 만족하는지 확인함.

In [8]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False], dtype=bool)

logical_not: not을 붙여줌

In [9]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False], dtype=bool)

logical_or: 괄호안에 조건중 하나만 만족하면 트루

In [10]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True], dtype=bool)

# np.where

where(condition, TRUE, FALSE) 으로 사용하여, 컨디션에 만족하면 트루일때의 값을 반환하고 만족하지 않으면 False일때의 값을 반환한다.

if와 비슷하다고 생각하면됨.

In [13]:
a = np.array([1, 3, 0], float)
a

array([ 1.,  3.,  0.])

In [14]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

condition만 들어갔으면 트루인 값의 인덱스를 반환한다.

In [15]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

np.isnan(a): 숫자가 아니면 ture 숫자이면 false

In [17]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

np.isfinite : 한정된 수면 ture 아니면 false

In [20]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

# argmax & argmin

arrary내 최댓값 또는 최솟값의 index를 반환함

In [24]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

axis 에 따라서도 출력할 수 있다.

In [29]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [32]:
np.argmax(a, axis=1)

array([3, 1, 1], dtype=int64)

In [33]:
np.argmin(a, axis=0)

array([0, 0, 2, 2], dtype=int64)