In [1]:
import numpy as np

# boolean index

numpy는 배열의 특정 조건에 따른 값을 배열 형태로 추출 할 수 있음

Comparison operation 함수들도 모두 사용가능

In [2]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True], dtype=bool)

불리언 타입의 arrary가 다시 arrary의 조건으로 들어가면 True인 index의 원소만 추출한다.

In [3]:
test_array[test_array > 3]

array([ 4.,  8.,  9.,  7.])

In [7]:
condition = test_array < 3 
test_array[condition]

array([ 1.,  0.,  2.])

불리언을 int로 바꾸면 true는 1, false는 0이됨

In [6]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int) #B를 int로 바꾸면 true는 1, false는 0이됨

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

# fancy index

넘파이는 arrry를 index value로 사용해서 값을 추출하는 법

In [9]:
a=np.array([2,4,6,8],float)
b=np.array([0,0,1,3,2,1],int)

fancy index를 사용하면 b값에 저장된 값들은 a에서 해당하는 index의 원소를 출력할 것이다.

단 반드시 b는 int 형태로 해야한다.

0:2

1:4

2:6

3:8

In [10]:
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

take함수가 같은 효과를 지닌다.

In [11]:
a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

matrix 형태로도 가능하다.

In [12]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] 

array([  1.,   4.,  16.,  16.,   4.])

b를 row index, c를 column index로 변환하여 표시함