In [1]:
import numpy as np

# loadtxt & savetxt

파일 호출

In [2]:
a = np.loadtxt("./populations.txt")
a[:10]

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.]])

데이터를 int type 변환

In [3]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

파일명을 int_data.csv로 저장

이때 데이터를 구분할때 기호(delimiter)는 쉼표로 하겠다.

In [5]:
np.savetxt('int_data.csv',a_int, delimiter=",")

# numpy object - npy

Numpy object(pickle)형태로 데이터를 저장하고 불러옴

Binary 파일 형태로 저장함

In [6]:
np.save("npy_test",arr=a_int)

불러오기

In [9]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])