# 14.예제

In [36]:
import tensorflow as tf
import numpy as np

In [22]:
x_data=[1,2,3]
y_data=[1,2,3]

W=tf.Variable(tf.random_normal([1]),name='weight')

X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

hypothesis = X*W

In [23]:
cost = tf.reduce_sum(tf.square(hypothesis - Y))

In [24]:
learning_rate = 0.1
gradient = tf.reduce_mean((W*X - Y)*X)
descent = W - learning_rate * gradient
update = W.assign(descent)

In [25]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [34]:
for step in range(21):
    sess.run(update, feed_dict={X:x_data, Y:y_data})
    print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}),sess.run(W))

0 1.54898e-12 [ 1.00000036]
1 7.95808e-13 [ 1.00000024]
2 2.98428e-13 [ 1.00000012]
3 0.0 [ 1.]
4 0.0 [ 1.]
5 0.0 [ 1.]
6 0.0 [ 1.]
7 0.0 [ 1.]
8 0.0 [ 1.]
9 0.0 [ 1.]
10 0.0 [ 1.]
11 0.0 [ 1.]
12 0.0 [ 1.]
13 0.0 [ 1.]
14 0.0 [ 1.]
15 0.0 [ 1.]
16 0.0 [ 1.]
17 0.0 [ 1.]
18 0.0 [ 1.]
19 0.0 [ 1.]
20 0.0 [ 1.]


# 다변량예측- 파일을 이용한 데이터 로딩

In [44]:
xy=np.loadtxt('multi_val_test_file.csv',delimiter=',',dtype=np.float32)

x_data =xy[:,0:-1]
y_data =xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [ ]:
X=placeholder(tf.float32, shape=[None,3])
Y=placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b= tf.Variable(tf.random_normal([1]),name='bias')